version: '3'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${APP_SECRET_KEY}
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: investimentos_bloxs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: