"""empty message

Revision ID: ec49350ff955
Revises: 
Create Date: 2023-03-09 19:44:26.618118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec49350ff955'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacao',
    sa.Column('idTransacao', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('dataTransacao', sa.DateTime(), nullable=True),
    sa.Column('idConta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idConta'], ['conta.idConta'], ),
    sa.PrimaryKeyConstraint('idTransacao')
    )
    op.drop_table('transacoes')
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.alter_column('saldo',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('limiteSaqueDiario',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('flagAtivo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('tipoConta',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('dataCriacao')

    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('cpf',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataCriacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.alter_column('tipoConta',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('flagAtivo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('limiteSaqueDiario',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)
        batch_op.alter_column('saldo',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)

    op.create_table('transacoes',
    sa.Column('idTransacao', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idConta', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('dataCriacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['idConta'], ['conta.idConta'], name='transacoes_ibfk_1'),
    sa.PrimaryKeyConstraint('idTransacao'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('transacao')
    # ### end Alembic commands ###
